FROM quay.io/fedora/fedora
RUN dnf -y update && dnf -y install \
		openssh-clients \
		git \
		golang \
		autoconf \
		make \
		bind-utils \
		telnet \
		nmap-ncat \
		nmap \
		podman \
		buildah

RUN dnf clean all
